# Generated by Django 5.0.2 on 2024-04-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_train',
            name='img',
            field=models.ImageField(null=True, upload_to='train_photos/'),
        ),
    ]
